import { QuizQuestion } from "../../../common/src";

export const DUMMY_QUESTIONS_DATA: QuizQuestion[] = [
  {
    id: 101,
    question: "What is the capital of France?",
    options: [
      { id: 1, text: "Paris" },
      { id: 2, text: "London" },
      { id: 3, text: "Berlin" },
      { id: 4, text: "Madrid" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 203,
    question: "Who is the founder of Microsoft?",
    options: [
      { id: 1, text: "Bill Gates" },
      { id: 2, text: "Steve Jobs" },
      { id: 3, text: "Elon Musk" },
      { id: 4, text: "Mark Zuckerberg" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 307,
    question: "Which planet is known as the Red Planet?",
    options: [
      { id: 1, text: "Mars" },
      { id: 2, text: "Jupiter" },
      { id: 3, text: "Saturn" },
      { id: 4, text: "Venus" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 411,
    question: "What is the chemical symbol for water?",
    options: [
      { id: 1, text: "H2O" },
      { id: 2, text: "O2" },
      { id: 3, text: "CO2" },
      { id: 4, text: "NaCl" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 518,
    question: "Which country is known as the Land of the Rising Sun?",
    options: [
      { id: 1, text: "Japan" },
      { id: 2, text: "China" },
      { id: 3, text: "South Korea" },
      { id: 4, text: "Thailand" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 623,
    question: "Who wrote 'To Kill a Mockingbird'?",
    options: [
      { id: 1, text: "Harper Lee" },
      { id: 2, text: "Mark Twain" },
      { id: 3, text: "F. Scott Fitzgerald" },
      { id: 4, text: "Ernest Hemingway" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 734,
    question: "What is the smallest prime number?",
    options: [
      { id: 1, text: "2" },
      { id: 2, text: "3" },
      { id: 3, text: "5" },
      { id: 4, text: "1" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 842,
    question: "Which element has the atomic number 1?",
    options: [
      { id: 1, text: "Hydrogen" },
      { id: 2, text: "Helium" },
      { id: 3, text: "Lithium" },
      { id: 4, text: "Carbon" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 956,
    question: "What is the capital of Australia?",
    options: [
      { id: 1, text: "Canberra" },
      { id: 2, text: "Sydney" },
      { id: 3, text: "Melbourne" },
      { id: 4, text: "Brisbane" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1068,
    question: "Which gas do plants primarily use for photosynthesis?",
    options: [
      { id: 1, text: "Carbon Dioxide" },
      { id: 2, text: "Oxygen" },
      { id: 3, text: "Nitrogen" },
      { id: 4, text: "Hydrogen" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1173,
    question: "Who painted the Mona Lisa?",
    options: [
      { id: 1, text: "Leonardo da Vinci" },
      { id: 2, text: "Vincent van Gogh" },
      { id: 3, text: "Pablo Picasso" },
      { id: 4, text: "Claude Monet" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1285,
    question: "What is the boiling point of water in Celsius?",
    options: [
      { id: 1, text: "100°C" },
      { id: 2, text: "0°C" },
      { id: 3, text: "50°C" },
      { id: 4, text: "75°C" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1394,
    question: "What is the main ingredient in guacamole?",
    options: [
      { id: 1, text: "Avocado" },
      { id: 2, text: "Tomato" },
      { id: 3, text: "Cucumber" },
      { id: 4, text: "Pepper" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1406,
    question: "What is the largest planet in our solar system?",
    options: [
      { id: 1, text: "Jupiter" },
      { id: 2, text: "Saturn" },
      { id: 3, text: "Neptune" },
      { id: 4, text: "Earth" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1521,
    question: "Who wrote 'Romeo and Juliet'?",
    options: [
      { id: 1, text: "William Shakespeare" },
      { id: 2, text: "Charles Dickens" },
      { id: 3, text: "Jane Austen" },
      { id: 4, text: "Mark Twain" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1634,
    question: "Which continent is the Sahara Desert located on?",
    options: [
      { id: 1, text: "Africa" },
      { id: 2, text: "Asia" },
      { id: 3, text: "Australia" },
      { id: 4, text: "North America" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1745,
    question: "What is the largest mammal in the world?",
    options: [
      { id: 1, text: "Blue Whale" },
      { id: 2, text: "Elephant" },
      { id: 3, text: "Giraffe" },
      { id: 4, text: "Rhino" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1852,
    question: "What is the square root of 64?",
    options: [
      { id: 1, text: "8" },
      { id: 2, text: "6" },
      { id: 3, text: "7" },
      { id: 4, text: "9" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 1963,
    question: "Which country is the largest by land area?",
    options: [
      { id: 1, text: "Russia" },
      { id: 2, text: "Canada" },
      { id: 3, text: "China" },
      { id: 4, text: "USA" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
  {
    id: 2074,
    question: "Which element is found in abundance in bananas?",
    options: [
      { id: 1, text: "Mg" },
      { id: 2, text: "Ag" },
      { id: 3, text: "Ca" },
      { id: 4, text: "K" },
    ],
    selectedOptionId: null,
    status: "default",
    markedForReview: false,
  },
];
